#include "token.h"

#include <unordered_map>

namespace yatsi {

static const std::unordered_map<std::string_view, TokenKind> keywords = {
    {"true", TokenKind::True},
    {"false", TokenKind::False},
    {"null", TokenKind::Null},
    {"undefined", TokenKind::Undefined},
    {"let", TokenKind::Let},
    {"const", TokenKind::Const},
    {"var", TokenKind::Var},
    {"function", TokenKind::Function},
    {"class", TokenKind::Class},
    {"extends", TokenKind::Extends},
    {"super", TokenKind::Super},
    {"new", TokenKind::New},
    {"this", TokenKind::This},
    {"return", TokenKind::Return},
    {"if", TokenKind::If},
    {"else", TokenKind::Else},
    {"while", TokenKind::While},
    {"for", TokenKind::For},
    {"do", TokenKind::Do},
    {"break", TokenKind::Break},
    {"continue", TokenKind::Continue},
    {"switch", TokenKind::Switch},
    {"case", TokenKind::Case},
    {"default", TokenKind::Default},
    {"throw", TokenKind::Throw},
    {"try", TokenKind::Try},
    {"catch", TokenKind::Catch},
    {"finally", TokenKind::Finally},
    {"typeof", TokenKind::TypeOf},
    {"instanceof", TokenKind::InstanceOf},
    {"in", TokenKind::In},
    {"of", TokenKind::Of},
    {"void", TokenKind::Void},
    {"delete", TokenKind::Delete},
    {"import", TokenKind::Import},
    {"export", TokenKind::Export},
    {"async", TokenKind::Async},
    {"await", TokenKind::Await},
    {"yield", TokenKind::Yield},
    {"enum", TokenKind::Enum},
    {"interface", TokenKind::Interface},
    {"type", TokenKind::Type},
    {"as", TokenKind::As},
    {"implements", TokenKind::Implements},
    {"declare", TokenKind::Declare},
    {"readonly", TokenKind::Readonly},
};

TokenKind lookup_keyword(const std::string &identifier) {
  auto it = keywords.find(identifier);
  if (it != keywords.end())
    return it->second;
  return TokenKind::Identifier;
}

// Transform a TokenKind enum entry to a friendly string
std::string_view token_kind_to_string(TokenKind kind) {
  switch (kind) {
  case TokenKind::Number:
    return "Number";
  case TokenKind::String:
    return "String";
  case TokenKind::TemplateHead:
    return "TemplateHead";
  case TokenKind::TemplateMiddle:
    return "TemplateMiddle";
  case TokenKind::TemplateTail:
    return "TemplateTail";
  case TokenKind::RegexLiteral:
    return "RegexLiteral";
  case TokenKind::NoSubstitutionTemplate:
    return "NoSubstitutionTemplate";
  case TokenKind::True:
    return "True";
  case TokenKind::False:
    return "False";
  case TokenKind::Null:
    return "Null";
  case TokenKind::Undefined:
    return "Undefined";
  case TokenKind::Let:
    return "Let";
  case TokenKind::Const:
    return "Const";
  case TokenKind::Var:
    return "Var";
  case TokenKind::Function:
    return "Function";
  case TokenKind::Class:
    return "Class";
  case TokenKind::Extends:
    return "Extends";
  case TokenKind::Super:
    return "Super";
  case TokenKind::New:
    return "New";
  case TokenKind::This:
    return "This";
  case TokenKind::Return:
    return "Return";
  case TokenKind::If:
    return "If";
  case TokenKind::Else:
    return "Else";
  case TokenKind::While:
    return "While";
  case TokenKind::For:
    return "For";
  case TokenKind::Do:
    return "Do";
  case TokenKind::Break:
    return "Break";
  case TokenKind::Continue:
    return "Continue";
  case TokenKind::Switch:
    return "Switch";
  case TokenKind::Case:
    return "Case";
  case TokenKind::Default:
    return "Default";
  case TokenKind::Throw:
    return "Throw";
  case TokenKind::Try:
    return "Try";
  case TokenKind::Catch:
    return "Catch";
  case TokenKind::Finally:
    return "Finally";
  case TokenKind::TypeOf:
    return "TypeOf";
  case TokenKind::InstanceOf:
    return "InstanceOf";
  case TokenKind::In:
    return "In";
  case TokenKind::Of:
    return "Of";
  case TokenKind::Void:
    return "Void";
  case TokenKind::Delete:
    return "Delete";
  case TokenKind::Import:
    return "Import";
  case TokenKind::Export:
    return "Export";
  case TokenKind::Async:
    return "Async";
  case TokenKind::Await:
    return "Await";
  case TokenKind::Yield:
    return "Yield";
  case TokenKind::Enum:
    return "Enum";
  case TokenKind::Interface:
    return "Interface";
  case TokenKind::Type:
    return "Type";
  case TokenKind::As:
    return "As";
  case TokenKind::Implements:
    return "Implements";
  case TokenKind::Declare:
    return "Declare";
  case TokenKind::Readonly:
    return "Readonly";
  case TokenKind::Plus:
    return "Plus";
  case TokenKind::Minus:
    return "Minus";
  case TokenKind::Star:
    return "Star";
  case TokenKind::Slash:
    return "Slash";
  case TokenKind::Percent:
    return "Percent";
  case TokenKind::StarStar:
    return "StarStar";
  case TokenKind::Equal:
    return "Equal";
  case TokenKind::PlusEqual:
    return "PlusEqual";
  case TokenKind::MinusEqual:
    return "MinusEqual";
  case TokenKind::StarEqual:
    return "StarEqual";
  case TokenKind::SlashEqual:
    return "SlashEqual";
  case TokenKind::PercentEqual:
    return "PercentEqual";
  case TokenKind::EqualEqual:
    return "EqualEqual";
  case TokenKind::EqualEqualEqual:
    return "EqualEqualEqual";
  case TokenKind::BangEqual:
    return "BangEqual";
  case TokenKind::BangEqualEqual:
    return "BangEqualEqual";
  case TokenKind::Less:
    return "Less";
  case TokenKind::LessEqual:
    return "LessEqual";
  case TokenKind::Greater:
    return "Greater";
  case TokenKind::GreaterEqual:
    return "GreaterEqual";
  case TokenKind::AmpersandAmpersand:
    return "AmpersandAmpersand";
  case TokenKind::PipePipe:
    return "PipePipe";
  case TokenKind::Bang:
    return "Bang";
  case TokenKind::QuestionQuestion:
    return "QuestionQuestion";
  case TokenKind::Ampersand:
    return "Ampersand";
  case TokenKind::Pipe:
    return "Pipe";
  case TokenKind::Caret:
    return "Caret";
  case TokenKind::Tilde:
    return "Tilde";
  case TokenKind::LessLess:
    return "LessLess";
  case TokenKind::GreaterGreater:
    return "GreaterGreater";
  case TokenKind::GreaterGreaterGreater:
    return "GreaterGreaterGreater";
  case TokenKind::PlusPlus:
    return "PlusPlus";
  case TokenKind::MinusMinus:
    return "MinusMinus";
  case TokenKind::Question:
    return "Question";
  case TokenKind::Arrow:
    return "Arrow";
  case TokenKind::Dot:
    return "Dot";
  case TokenKind::DotDotDot:
    return "DotDotDot";
  case TokenKind::LeftParen:
    return "LeftParen";
  case TokenKind::RightParen:
    return "RightParen";
  case TokenKind::LeftBrace:
    return "LeftBrace";
  case TokenKind::RightBrace:
    return "RightBrace";
  case TokenKind::LeftBracket:
    return "LeftBracket";
  case TokenKind::RightBracket:
    return "RightBracket";
  case TokenKind::Semicolon:
    return "Semicolon";
  case TokenKind::Comma:
    return "Comma";
  case TokenKind::Colon:
    return "Colon";
  case TokenKind::Identifier:
    return "Identifier";
  case TokenKind::EndOfFile:
    return "EndOfFile";
  case TokenKind::Error:
    return "Error";
  }
  return "Unknown";
}

} // namespace yatsi
