import type { EvalResult, ErrorPhase } from '../types/engine';

interface WasmEvalResult {
  success: boolean;
  error_type: string;
  error_message: string;
  phase: number;
  console_output: string;
}

interface YatsiModule {
  evaluate(source: string): WasmEvalResult;
}

type CreateYatsi = () => Promise<YatsiModule>;

const PHASE_MAP: Record<number, ErrorPhase> = {
  0: 'none',
  1: 'parse',
  2: 'runtime',
};

export class YatsiEngine {
  private constructor(private module: YatsiModule) {}

  static async create(): Promise<YatsiEngine> {
    // @ts-ignore — WASM glue code generated by Emscripten, not present at type-check time
    const { default: createYatsi } = await import('./wasm/yatsi.js');
    const module = await (createYatsi as CreateYatsi)();
    return new YatsiEngine(module);
  }

  evaluate(source: string): EvalResult {
    const raw = this.module.evaluate(source);
    return {
      success: raw.success,
      errorType: raw.error_type,
      errorMessage: raw.error_message,
      phase: PHASE_MAP[raw.phase] ?? 'runtime',
      consoleOutput: raw.console_output,
    };
  }

  destroy(): void {
    // Future: call module cleanup if needed
  }
}
