import type { EvalResult, ErrorPhase } from '../types/engine';

interface WasmEvalResult {
  success: boolean;
  error_type: string;
  error_message: string;
  phase: number;
  console_output: string;
}

interface YatsiModule {
  evaluate(source: string): WasmEvalResult;
  typecheck_as_eval(source: string): WasmEvalResult;
  dump_typed_ast_as_eval(source: string): WasmEvalResult;
  run_pipeline(source: string): string;
  tokenize_traced(source: string): string;
  parse_traced(source: string): string;
  compile_traced(source: string): string;
  execute_traced(source: string): string;
  typecheck_traced(source: string): string;
}

type CreateYatsi = () => Promise<YatsiModule>;

const PHASE_MAP: Record<number, ErrorPhase> = {
  0: 'none',
  1: 'parse',
  2: 'runtime',
};

export class YatsiEngine {
  private constructor(private module: YatsiModule) {}

  static async create(): Promise<YatsiEngine> {
    // @ts-ignore — WASM glue code generated by Emscripten, not present at type-check time
    const { default: createYatsi } = await import('./wasm/yatsi.js');
    const module = await (createYatsi as CreateYatsi)();
    return new YatsiEngine(module);
  }

  evaluate(source: string): EvalResult {
    const raw = this.module.evaluate(source);
    return {
      success: raw.success,
      errorType: raw.error_type,
      errorMessage: raw.error_message,
      phase: PHASE_MAP[raw.phase] ?? 'runtime',
      consoleOutput: raw.console_output,
    };
  }

  typecheck(source: string): EvalResult {
    const raw = this.module.typecheck_as_eval(source);
    return {
      success: raw.success,
      errorType: raw.error_type,
      errorMessage: raw.error_message,
      phase: PHASE_MAP[raw.phase] ?? 'runtime',
      consoleOutput: raw.console_output,
    };
  }

  dumpTypedAst(source: string): EvalResult {
    const raw = this.module.dump_typed_ast_as_eval(source);
    return {
      success: raw.success,
      errorType: raw.error_type,
      errorMessage: raw.error_message,
      phase: PHASE_MAP[raw.phase] ?? 'runtime',
      consoleOutput: raw.console_output,
    };
  }

  runPipeline(source: string): string {
    return this.module.run_pipeline(source);
  }

  tokenizeTraced(source: string): string {
    return this.module.tokenize_traced(source);
  }

  parseTraced(source: string): string {
    return this.module.parse_traced(source);
  }

  compileTraced(source: string): string {
    return this.module.compile_traced(source);
  }

  executeTraced(source: string): string {
    return this.module.execute_traced(source);
  }

  typecheckTraced(source: string): string {
    return this.module.typecheck_traced(source);
  }

  destroy(): void {
    // Future: call module cleanup if needed
  }
}
